### ISSUE TITLE
Leaf Carpets Are Very Slow To Break

### ISSUE THREAD

**Issue by Greymanz** [minecraftabnormals/Autumnity#27]
Leaf Carpets should be functionally identical to other decorative plants. The break time for them is extremely long making it a pain to clear out large sections for a home. Decreasing the breaking time to be more in line with vanilla objects like grass or flowers would be best.

**Comment by bageldotjpg** [comment]
They work in-line with Quark's Leaf Carpets. In 1.16.3, they will break instantly to go alongside Quark's.
