### ISSUE TITLE
Leaf Carpets Drop Their Item even when not using Shears

### ISSUE THREAD

**Issue by Greymanz** [minecraftabnormals/Autumnity#28]
Usually plant decoratives in Minecraft do not drop their respective item normally, especially if its abundant and/or cosmetic like grass and ferns. Although you could certainly add some sort of semi-rare "Seed like" drop for the leaf piles, having stacks of leaves fill up my inventory is a real pain. They should be treated like other cosmetic plants, you can only obtain them with shears.

**Comment by bageldotjpg** [comment]
Intended, to work like how Quark's work.

**Comment by Brun333rp** [comment]
does that means that leaf carpets not being affected by gravity is also intended? I was going to report it here right now, but I think that this is something to report on Quark's github

**Comment by bageldotjpg** [comment]
yes its intended on both, it can be used decoratively
